language: node_js
node_js:
- 8.14.0
install: 
  - npm install -g add travis-ci-cloudfront-invalidation
  - npm install
script: gatsby build
branches:
  only:
      - master
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "tingsthings.com"
  skip_cleanup: true
  acl: public_read
  local_dir: public
  region: us-west-1
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_KEY -s $AWS_SECRET -c $CF_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST